default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: worth-chicago_co_development

test: &test
  <<: *default
  database: worth-chicago_co_test<%=ENV['TEST_ENV_NUMBER']%>

production:
  <<: *default
  database: worth-chicago_co_production
  username: worth-chicago_co
  password: <%= ENV['WORTH-CHICAGO_CO_DATABASE_PASSWORD'] %>

cucumber:
  <<: *test
